### Get Pets
GET http://localhost:3333/pets

### Create Pet
POST http://localhost:3333/pets
Content-Type: application/json

{

  "name": "lechado",
  "type": "Cachorro", 
  "photo": "URLDaFotoDoPet",
  "owners": {
    "connect": {
      "id": "c49a81f7-9475-48e4-9a37-d72254251341"
    }
  }
}

### Update Pet ID
Update Pet Type
PUT http://localhost:3333/pets/marmota/updatePet
Content-Type: application/json
{
  "newId":"marmota",
  "name": "marmota",
  "type": "marmota",
}

### Get pet id
GET http://localhost:3333/pets/vb4Gumt4U


### Delete Pet
DELETE http://localhost:3333/pets/