GET http://localhost:3000/

### Delete Pets
DELETE http://localhost:3000/pets/WHJu7iBJg6

### Get Pets
GET http://localhost:3000/pets

### Change Pets name
PUT http://localhost:3000/pets/updateName/cbhELTs5hi
Content-Type: application/json


{
    "newName": "Trambolho"
}

### Change Pets type
PUT http://localhost:3000/pets/updateType/cbhELTs5hi
Content-Type: application/json


{
    "newType": "outros"
}

### Update Pet id
PUT http://localhost:3000/pets/updateId/DnakbD7aJS
Content-Type: application/json

{
    "newId": "neymar"
}

### Create Pets
POST http://localhost:3000/pets
Content-Type: application/json



{
    "name": "Belinha",
    "type": "cachorro",
    "password": "A1234567.a",
    "confirmPassword": "A1234567.a",
    "birthdate": "20/09/2001"
}
