### Get Pets
GET http://localhost:3333/pets

### Create Pet
POST http://localhost:3333/pets
Content-Type: application/json

{
  "name": "Belinha",
  "type": "Cachorro", 
  "photo": "URLDaFotoDoPet",
  "owners": {
    "connect": {
      "id": "f571a065-c870-4d05-8a6f-4f0099d8d3fe"
    }
  }
}

### Update Pet ID
Update Pet Type
PUT http://localhost:3333/pets/marmota/updatePet
Content-Type: application/json
{
  "newId":"marmota",
  "name": "marmota",
  "type": "marmota",
}

### Get pet id
GET http://localhost:3333/pets/vb4Gumt4U


### Delete Pet
DELETE http://localhost:3333/pets/OEOZZw9LO