GET http://localhost:3333/

### Get Users
GET http://localhost:3333/users

### Get User
GET http://localhost:3333/users/1ed5d227-7f6b-4ae5-88cc-b0f87c5dfaed

### Create User
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "calvo",
    "email": "calvo9@calvo.calvo",
    "password": "A12345697.a"
}

### Update User
PUT  http://localhost:3333/users/
Content-Type: application/json

{
    "name": "up",
    "email": "calvo@calvo.calvo",
    "password": "A1234567.a",
}

### Excluir um Usuário por ID
DELETE http://localhost:3333/users/a937ad56-1e25-4902-b516-9c6ee844b5e2s

### Autenticação
POST http://localhost:3333/auth
Content-Type: application/json

{
    "email": "calvo9@calvo.calvo",
    "password": "A12345697.a"
}