GET http://localhost:3333/

### Get Users
GET http://localhost:3333/users

### Get User
GET http://localhost:3333/users/7dcf243c-8391-48b6-a5e7-501339848802

### Create User
POST http://localhost:3333/users/
Content-Type: application/json

{
    "name": "flepes flopes",
    "email": "flopes@email.com",
    "password": "A1234567.a"
}

### Update User
PUT http://localhost:3333/users/ca8d6ec8-1e4c-4373-9e4f-3cc9c7f5a395
Content-Type: application/json

{
    "name": "calvofelipepoderosoN555o000me",
    "email": "novoemail@calvo.com",
    "password": "NovaS.enha123a"
}

### Excluir um Usuário por ID
DELETE http://localhost:3333/users/d9586b2d-62a9-4fce-9219-5db5322f81fc

### Listar pets do user
GET http://localhost:3333/users/pets/c7d2d121-4168-4800-bfed-6eb2a07b9daa

### Convidar Usuario por email
POST http://localhost:3333/users/invite/g@c.com
Content-Type: application/json

{
    "petId": "zlklj0Vjb"
}


// explode o back end com cntrl c
// e da --> yarn start:dev <-- de volta
// pra gente ver
