### Get Pets
GET http://localhost:3333/pets

### Create Pet
POST http://localhost:3333/pets
Content-Type: application/json

{
  "name": "Vo Cleus444",
  "type": "Humano",
  "password": "A.1234567a",
  "confirmPassword": "A.1234567a", 
  "photo": "URLDaFotoDoPet",
  "owners": {
    "connect": {
      "id": "02674c9e-08cc-4226-81cf-010551b14866"
    }
  }
}

### Update Pet ID
Update Pet Type
PUT http://localhost:3333/pets/marmota/updatePet
Content-Type: application/json
{
  "newId":"marmota",
  "name": "marmota",
  "type": "marmota",
}

### Get pet id
GET http://localhost:3333/pets/VMx1BeiXx


### Delete Pet
DELETE http://localhost:3333/pets/D3HsssX74