GET http://localhost:3333/

### Get Users
GET http://localhost:3333/users

### Get User
GET http://localhost:3333/users/7dcf243c-8391-48b6-a5e7-501339848802

### Create User
POST http://localhost:3333/users/
Content-Type: application/json

{
    "name": "Clayson",
    "email": "clayson@email.com",
    "password": "A1234567.a"
}
### Update User
PUT http://localhost:3333/users/ca8d6ec8-1e4c-4373-9e4f-3cc9c7f5a395
Content-Type: application/json

{
    "name": "calvofelipepoderosoN555o000me",
    "email": "novoemail@calvo.com",
    "password": "NovaS.enha123a"
}

### Excluir um Usuário por ID
DELETE http://localhost:3333/users/a937ad56-1e25-4902-b516-9c6ee844b5e2s

### Listar pets do user
GET http://localhost:3333/users/pets/a3afc032-10b0-4014-ad04-f61f1a16ca6a

### Convidar Usuario por email
POST http://localhost:3333/users/invite/clayson@email.com
Content-Type: application/json

{
    "petId": "wzYjuPOCr"
    
}