GET http://localhost:3333/

### Get Users
GET http://localhost:3333/users

### Get User
GET http://localhost:3333/users/7dcf243c-8391-48b6-a5e7-501339848802

### Create User
POST http://localhost:3333/users/
Content-Type: application/json

{
    "name": "flebes",
    "email": "flebes@email.com",
    "password": "A1234567.a"
}
### Update User
PUT http://localhost:3333/users/ca8d6ec8-1e4c-4373-9e4f-3cc9c7f5a395
Content-Type: application/json

{
    "name": "calvofelipepoderosoN555o000me",
    "email": "novoemail@calvo.com",
    "password": "NovaS.enha123a"
}

### Excluir um Usuário por ID
DELETE http://localhost:3333/users/e94a98fe-7357-4e55-b098-7224f7be4de9

### Listar pets do user
GET http://localhost:3333/users/pets/a3afc032-10b0-4014-ad04-f61f1a16ca6a

### Convidar Usuario por email
POST http://localhost:3333/users/invite/flobes@email.com
Content-Type: application/json

{
    "petId": "21a2806a-f71e-49ad-ad0d-eb37d0de93ce" 
}