### Get Pets
GET http://localhost:3333/pets

### Create Pet
POST http://localhost:3333/pets
Content-Type: application/json

{
  "name": "Vo Cleusa",
  "type": "Humano",
  "password": "A.1234567a",
  "confirmPassword": "A.1234567a", 
  "photo": "URLDaFotoDoPet",
  "owners": {
    "connect": {
      "id": "82e43531-2e66-43fb-9373-7e34dce5d2a8"
    }
  }
}

### Update Pet ID
Update Pet Type
PUT http://localhost:3333/pets/marmota/updatePet
Content-Type: application/json
{
  "newId":"marmota",
  "name": "marmota",
  "type": "marmota",
}

###Get pet by user id
GET http://localhost:3333/pets/82e43531-2e66-43fb-9373-7e34dce5d2a8 

### Delete Pet
DELETE http://localhost:3333/pets/Yj668suiFD